/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.print.PrinterException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controller.SocketServer;
import Model.OrderStatus;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author shreejal
 */
public class ServerFrame extends javax.swing.JFrame {

	/**
	 * Creates new form ClientFrame
	 */

	DataInputStream dis = null;
	public SocketServer server;
	Socket socket;
	public Thread serverThread;

	public ServerFrame() throws IOException {
		initComponents();
		ta_server.setEditable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_startServer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_server = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cash_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        b_print = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Bill_Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        b_Add_For_Bill = new javax.swing.JButton();
        b_Calc_Total = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_startServer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_startServer.setText("Start Server");
        b_startServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_startServerActionPerformed(evt);
            }
        });

        ta_server.setColumns(20);
        ta_server.setRows(5);
        jScrollPane1.setViewportView(ta_server);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cash_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "momo",  new Integer(3), "DELIVERED",  new Integer(100)}
            },
            new String [] {
                "TableNo", "Dish Name", "Quantity", "Order Status", "Unit Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Cash_table.setRowHeight(20);
        jScrollPane2.setViewportView(Cash_table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Table  No.:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        b_print.setText("Print");
        b_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_printActionPerformed(evt);
            }
        });

        Bill_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish Name", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Bill_Table.setRowHeight(20);
        jScrollPane3.setViewportView(Bill_Table);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Generate Bill : : :");

        b_Add_For_Bill.setText("Add For Bill");
        b_Add_For_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Add_For_BillActionPerformed(evt);
            }
        });

        b_Calc_Total.setText("Calculate Total");
        b_Calc_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Calc_TotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_startServer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_print, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_Calc_Total))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_Add_For_Bill)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_startServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_Add_For_Bill)
                        .addGap(4, 4, 4)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(b_Calc_Total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_print)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void b_Add_For_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Add_For_BillActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) Cash_table.getModel();
        int[] index = Cash_table.getSelectedRows();
        Object rowData[] = new Object[5];
       
        
        for(int i=0;i<index.length;i++)
        {
           // rowData[0] = model.getValueAt(index[i],0);
            rowData[0] = model.getValueAt(index[i],1);
            rowData[1] = model.getValueAt(index[i],2);
            rowData[2] = model.getValueAt(index[i],4);
            rowData[3] = Integer.parseInt(model.getValueAt(index[i],2).toString()) * Integer.parseInt(model.getValueAt(index[i],4).toString());
            DefaultTableModel model2 = (DefaultTableModel) Bill_Table.getModel();
          
            if(Bill_Table.getRowCount() ==0){
                model.removeRow(index[i]);
                model2.addRow(rowData);
            }
            
            else if("Grand Total".equals(model2.getValueAt(Bill_Table.getRowCount()-1, 2).toString())){
                model2.removeRow(Bill_Table.getRowCount()-1);
                model.removeRow(index[i]);
                model2.addRow(rowData);
            }
            else{
                model.removeRow(index[i]);
                model2.addRow(rowData);
            }
        }
    }//GEN-LAST:event_b_Add_For_BillActionPerformed

    private void b_Calc_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Calc_TotalActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) Bill_Table.getModel();
        double z = 0;
        if("Grand Total".equals(model.getValueAt(Bill_Table.getRowCount()-1, 2).toString()))
        {
           // JOptionPane.showConfirmDialog(null, "Total Already Calculated!!\n Wanted to remove it??", "Confirm Total Calculation", JOptionPane.YES_NO_OPTION, JOptionPane.YES_OPTION);
            //if(JOptionPane.YES_NO_OPTION == 1){
           // model.removeRow(Bill_Table.getRowCount()-1);
           // }
            JOptionPane.showMessageDialog(null, "Grand Total Already Calculated!!!");
        }
        else{
        for(int y=0; y < Bill_Table.getRowCount(); y++){
            z+=Double.parseDouble(Bill_Table.getValueAt(y, 3).toString());
        }
         model.addRow(new Object[]{null,null,"Grand Total",z});
         }
        
    }//GEN-LAST:event_b_Calc_TotalActionPerformed

	private void b_startServerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b_startServerActionPerformed
		// TODO add your handling code here:\
		server = new SocketServer(this);
		b_startServer.setEnabled(false);
	}// GEN-LAST:event_b_startServerActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
	
	// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	private void b_printActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b_printActionPerformed
		// TODO add your handling code here:

		try {
			Boolean complete = Bill_Table.print();

			if (complete) {
				JOptionPane.showMessageDialog(null, "Succesfully Printed.");
			} else {
				JOptionPane.showMessageDialog(null, "Printing Cancelled.");
			}
		} catch (PrinterException ex) {

			JOptionPane.showMessageDialog(null, ex);
			Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE,null, ex);
		}
	}// GEN-LAST:event_b_printActionPerformed

	public void RetryStart(int port) {
		if (server != null) {
			server.stop();
		}
		server = new SocketServer(this, port);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ServerFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new ServerFrame().setVisible(true);
				} catch (IOException ex) {
					Logger.getLogger(ServerFrame.class.getName()).log(
							Level.SEVERE, null, ex);
				}
			}
		});
		// DataInputStream dis = new DataInputStream(Socket.getInputStream());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Bill_Table;
    public javax.swing.JTable Cash_table;
    private javax.swing.JButton b_Add_For_Bill;
    private javax.swing.JButton b_Calc_Total;
    private javax.swing.JButton b_print;
    private javax.swing.JButton b_startServer;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextArea ta_server;
    // End of variables declaration//GEN-END:variables
}